export const userData = [
  {
    id: 1,
    name: "Asif Vudi",
    amount: 345,
    lastPurchase: "2 March 23",
  },
  {
    id: 2,
    name: "Sabuj Ahmed",
    amount: 356,
    lastPurchase: "4 March 23",
  },
  {
    id: 3,
    name: "Shohag Ahmed",
    amount: 355,
    lastPurchase: "10 March 23",
  },
  {
    id: 4,
    name: "Shehab Uddin",
    amount: 567,
    lastPurchase: "14 March 23",
  },
  {
    id: 5,
    name: "Babu Farazi",
    amount: 600,
    lastPurchase: "5 March 23",
  },
  {
    id: 6,
    name: "Nur Anar",
    amount: 355,
    lastPurchase: "10 March 23",
  },
  {
    id: 7,
    name: "John Doe",
    amount: 400,
    lastPurchase: "12 March 23",
  },
  {
    id: 8,
    name: "Jane Smith",
    amount: 250,
    lastPurchase: "20 March 23",
  },
  {
    id: 9,
    name: "David Johnson",
    amount: 500,
    lastPurchase: "18 March 23",
  },
  {
    id: 10,
    name: "Emily Brown",
    amount: 700,
    lastPurchase: "8 March 23",
  },
  {
    id: 11,
    name: "Michael Wilson",
    amount: 450,
    lastPurchase: "6 March 23",
  },
  {
    id: 12,
    name: "Sarah Thompson",
    amount: 550,
    lastPurchase: "22 March 23",
  },
  {
    id: 13,
    name: "Christopher Martinez",
    amount: 300,
    lastPurchase: "16 March 23",
  },
  {
    id: 14,
    name: "Jessica Davis",
    amount: 420,
    lastPurchase: "11 March 23",
  },
  {
    id: 15,
    name: "Daniel Garcia",
    amount: 380,
    lastPurchase: "9 March 23",
  },
];

export const productData = [
  {
    id: "1",
    product: "Ibuprofen",
    price: "$1234",
    category: "Category 1",
  },
  {
    id: "2",
    product: "Acetaminophen",
    price: "$1234",
    category: "Category 2",
  },
  {
    id: "3",
    product: "Aspirin",
    price: "$1234",
    category: "Category 1",
  },
  {
    id: "4",
    product: "Band-Aids",
    price: "$1234",
    category: "Category 3",
  },
  {
    id: "5",
    product: "Antiseptic Solution",
    price: "$1234",
    category: "Category 2",
  },
  {
    id: "6",
    product: "Thermometer",
    price: "$1234",
    category: "Category 3",
  },
  {
    id: "7",
    product: "Antibiotic Ointment",
    price: "$1234",
    category: "Category 1",
  },
  {
    id: "8",
    product: "Gauze Pads",
    price: "$1234",
    category: "Category 2",
  },
  {
    id: "9",
    product: "Hydrogen Peroxide",
    price: "$1234",
    category: "Category 3",
  },
  {
    id: "10",
    product: "Cough Syrup",
    price: "$1234",
    category: "Category 1",
  },
  {
    id: "11",
    product: "Antihistamine",
    price: "$1234",
    category: "Category 2",
  },
  {
    id: "12",
    product: "First Aid Kit",
    price: "$1234",
    category: "Category 3",
  },
  {
    id: "13",
    product: "Medical Gloves",
    price: "$1234",
    category: "Category 1",
  },
  {
    id: "14",
    product: "Digital Blood Pressure Monitor",
    price: "$1234",
    category: "Category 2",
  },
  {
    id: "15",
    product: "Disposable Face Masks",
    price: "$1234",
    category: "Category 3",
  },
];
